stages:
  - deploy
  - run
  - tests

npm-run:
  stage: run
  image: pooepw/coviddb:dev # change to correct image
  script:
  - ls
  - cd react
  - ls
  - npm install
  - CI=false npm run-script build

image: node:latest

test_python:
  stage: tests
  image: python:latest
  script:
    - cd back
    - apt-get install -y python3-pip python3-dev build-essential vim
    - apt-get -y install nginx
    - sudo apt-get install libpq-dev
    - pip install -r requirements.txt
    - python test.py

deploy_develop:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout dev
  script:
    - cd back
    - /root/.local/bin/eb deploy coviddb-api-prod # TODO change to coviddb-api-dev

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - cd back
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout main
  script:
    - /root/.local/bin/eb deploy coviddb-api-prod
