stages:
  - deploy
  - run
  - test

npm-run:
  stage: run
  image: pooepw/coviddb:dev
  script:
  - ls
  - cd react
  - ls
  - npm install
  - CI=false npm run-script build

image: node:latest

deploy_develop:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout dev
  script:
    - cd back
    - /root/.local/bin/eb deploy coviddb-api-prod # TODO change to coviddb-api-dev

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - cd back
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout main
  script:
    - /root/.local/bin/eb deploy coviddb-api-prod

postman_tests:
  stage: test
  image: 
    name: postman/newman_alpine33
    entrypoint: [""]
  script:
    - newman --version

backend_tests:
  stage: test
  image: python:3.6-stretch
  script:
    - cd back
    - pip install -r requirements.txt
    - python test.py