stages:
  - deploy
  - run

npm-run:
  stage: run
  image: pooepw/coviddb:dev # change to correct image
  script:
  - ls
  - cd react
  - ls
  - npm install
  - CI=false npm run-script build

image: node:latest

deploy_develop:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout dev
  script:
    - cd back
    - /root/.local/bin/eb deploy coviddb-api-prod # TODO change to coviddb-api-dev

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - pip install awsebcli --upgrade --user
    - cd back
    - chmod +x ./.eb-config.sh
    - ./.eb-config.sh
    - git checkout main
  script:
    - /root/.local/bin/eb deploy coviddb-api-prod

gui_tests:
  image: python:3.7
  script:
    - pip install selenium
    - cd react

    - apt-get update -q -y
    - apt-get install nodejs npm -y
    - apt-get --yes install libnss3
    - apt-get --yes install libgconf-2-4
    - apt-get install libx11-xcb1

    - curl -sS -L https://dl.google.com/linux/linux_signing_key.pub | 
      apt-key add -

    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ 
      stable main" > /etc/apt/sources.list.d/google.list
    - apt-get update -q -y
    - apt-get install -y google-chrome-stable
    - npm install

    - python3 gui_tests.py