stages:
  - deploy
  - run

npm-run:
  stage: run
  image: pooepw/coviddb:dev # change to correct image
  script:
  - ls
  - cd react
  - ls
  - npm install
  - CI=false npm run-script build

image: node:latest

deploy_develop:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "dev"
  stage: deploy
  before_script:
    - git checkout dev
  script:
    - git checkout dev

deploy_production:
  image: python:3.6-stretch
  only:
    variables:
      - $CI_COMMIT_BRANCH == "main"
  stage: deploy
  before_script:
    - git checkout main
  script:
    - git checkout dev
